### PR TITLE
#1 - seconds --> milliseconds

### PR DESCRIPTION
**Pull request by pokerjocke70**
Removed divide by 1000.

### CODE REVIEW

**Comment by jackspaniel** [comment]
This looks good - and thanks for creating tests too. You may be the first person actually using this (my company hasn't used it yet). So feel free to reach out with any other questions, comments or issues.

**Comment by pokerjocke70** [comment]
Any possibility to upload a new version with the fix?

**Comment by jackspaniel** [comment]
Oh yeah - forgot about that part!

**Comment by jackspaniel** [comment]
Done.

**Comment by pokerjocke70** [comment]
Thanks

**Pull request merged**
